import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

type Props = {
  movieSearch: string;
};

const Search: NextPage = (Props) => {
  const router = useRouter();
  const { movieSearch } = router.query;
  return (
    <>
      <Head>
        <title>{movieSearch}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-center text-4xl ">Search page for: {}</div>
      </main>

      <footer></footer>
    </>
  );
};

export default Search;
